# ==========================================================================
# yazi.toml — main yazi configuration
# ==========================================================================

[manager]
sort_by        = "natural"
sort_sensitive = false
sort_dir_first = true
show_hidden    = false
show_symlink   = true

[opener]
edit = [
  { run = 'nvim "$@"', block = true, desc = "Edit in nvim" },
]
